### ISSUE TITLE
vue.runtime.js?4b76:1888 TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by xoxoj** [inertiajs/inertia-vue#32] opened 2019-05-16 04:08 UTC
`vue.runtime.js?4b76:625 [Vue warn]: Error in render: "TypeError: Cannot read property 'apply' of undefined"

found in

---> <MainMenu> at resources/js/Shared/MainMenu.vue
       <Layout> at resources/js/Shared/Layout.vue
         <Index> at resources/js/Pages/Dashboard/Index.vue
           <Inertia>
             <Root>
warn @ vue.runtime.js?4b76:625
logError @ vue.runtime.js?4b76:1884
globalHandleError @ vue.runtime.js?4b76:1879
handleError @ vue.runtime.js?4b76:1839
Vue._render @ vue.runtime.js?4b76:3538
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
createChildren @ vue.runtime.js?4b76:6031
createElm @ vue.runtime.js?4b76:5932
patch @ vue.runtime.js?4b76:6453
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6453
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3934
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
run @ vue.runtime.js?4b76:4538
flushSchedulerQueue @ vue.runtime.js?4b76:4296
(anonymous) @ vue.runtime.js?4b76:1980
flushCallbacks @ vue.runtime.js?4b76:1906
Promise.then (async)
timerFunc @ vue.runtime.js?4b76:1933
nextTick @ vue.runtime.js?4b76:1990
queueWatcher @ vue.runtime.js?4b76:4388
update @ vue.runtime.js?4b76:4528
notify @ vue.runtime.js?4b76:736
reactiveSetter @ vue.runtime.js?4b76:1061
(anonymous) @ app.js?439b:33
Promise.then (async)
(anonymous) @ app.js?439b:32
init @ inertia.js?0375:18
created @ app.js?439b:31
invokeWithErrorHandling @ vue.runtime.js?4b76:1854
callHook @ vue.runtime.js?4b76:4205
Vue._init @ vue.runtime.js?4b76:4987
VueComponent @ vue.runtime.js?4b76:5132
createComponentInstanceForVnode @ vue.runtime.js?4b76:3281
init @ vue.runtime.js?4b76:3112
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
(anonymous) @ app.js?6d40:19
./resources/js/app.js @ app.js?id=5d43c79e331d5c766823:680
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
0 @ app.js?id=5d43c79e331d5c766823:702
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
(anonymous) @ app.js?id=5d43c79e331d5c766823:196
(anonymous) @ app.js?id=5d43c79e331d5c766823:199
Show 13 more frames
vue.runtime.js?4b76:1888 TypeError: Cannot read property 'apply' of undefined
    at VueComponent.route (app.js?6d40:4)
    at Proxy.render (MainMenu.vue?9c49:64)
    at VueComponent.Vue._render (vue.runtime.js?4b76:3536)
    at VueComponent.updateComponent (vue.runtime.js?4b76:4052)
    at Watcher.get (vue.runtime.js?4b76:4463)
    at new Watcher (vue.runtime.js?4b76:4452)
    at mountComponent (vue.runtime.js?4b76:4059)
    at VueComponent.Vue.$mount (vue.runtime.js?4b76:8390)
    at init (vue.runtime.js?4b76:3116)
    at createComponent (vue.runtime.js?4b76:5956)
logError @ vue.runtime.js?4b76:1888
globalHandleError @ vue.runtime.js?4b76:1879
handleError @ vue.runtime.js?4b76:1839
Vue._render @ vue.runtime.js?4b76:3538
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
createChildren @ vue.runtime.js?4b76:6031
createElm @ vue.runtime.js?4b76:5932
patch @ vue.runtime.js?4b76:6453
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6453
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
init @ vue.runtime.js?4b76:3116
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3934
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
run @ vue.runtime.js?4b76:4538
flushSchedulerQueue @ vue.runtime.js?4b76:4296
(anonymous) @ vue.runtime.js?4b76:1980
flushCallbacks @ vue.runtime.js?4b76:1906
Promise.then (async)
timerFunc @ vue.runtime.js?4b76:1933
nextTick @ vue.runtime.js?4b76:1990
queueWatcher @ vue.runtime.js?4b76:4388
update @ vue.runtime.js?4b76:4528
notify @ vue.runtime.js?4b76:736
reactiveSetter @ vue.runtime.js?4b76:1061
(anonymous) @ app.js?439b:33
Promise.then (async)
(anonymous) @ app.js?439b:32
init @ inertia.js?0375:18
created @ app.js?439b:31
invokeWithErrorHandling @ vue.runtime.js?4b76:1854
callHook @ vue.runtime.js?4b76:4205
Vue._init @ vue.runtime.js?4b76:4987
VueComponent @ vue.runtime.js?4b76:5132
createComponentInstanceForVnode @ vue.runtime.js?4b76:3281
init @ vue.runtime.js?4b76:3112
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
(anonymous) @ app.js?6d40:19
./resources/js/app.js @ app.js?id=5d43c79e331d5c766823:680
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
0 @ app.js?id=5d43c79e331d5c766823:702
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
(anonymous) @ app.js?id=5d43c79e331d5c766823:196
(anonymous) @ app.js?id=5d43c79e331d5c766823:199
Show 12 more frames
vue.runtime.js?4b76:625 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'app' of undefined"

found in

---> <Layout> at resources/js/Shared/Layout.vue
       <Index> at resources/js/Pages/Dashboard/Index.vue
         <Inertia>
           <Root>
warn @ vue.runtime.js?4b76:625
logError @ vue.runtime.js?4b76:1884
globalHandleError @ vue.runtime.js?4b76:1879
handleError @ vue.runtime.js?4b76:1839
invokeWithErrorHandling @ vue.runtime.js?4b76:1862
callHook @ vue.runtime.js?4b76:4205
insert @ vue.runtime.js?4b76:3137
invokeInsertHook @ vue.runtime.js?4b76:6324
patch @ vue.runtime.js?4b76:6541
Vue._update @ vue.runtime.js?4b76:3934
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
run @ vue.runtime.js?4b76:4538
flushSchedulerQueue @ vue.runtime.js?4b76:4296
(anonymous) @ vue.runtime.js?4b76:1980
flushCallbacks @ vue.runtime.js?4b76:1906
Promise.then (async)
timerFunc @ vue.runtime.js?4b76:1933
nextTick @ vue.runtime.js?4b76:1990
queueWatcher @ vue.runtime.js?4b76:4388
update @ vue.runtime.js?4b76:4528
notify @ vue.runtime.js?4b76:736
reactiveSetter @ vue.runtime.js?4b76:1061
(anonymous) @ app.js?439b:33
Promise.then (async)
(anonymous) @ app.js?439b:32
init @ inertia.js?0375:18
created @ app.js?439b:31
invokeWithErrorHandling @ vue.runtime.js?4b76:1854
callHook @ vue.runtime.js?4b76:4205
Vue._init @ vue.runtime.js?4b76:4987
VueComponent @ vue.runtime.js?4b76:5132
createComponentInstanceForVnode @ vue.runtime.js?4b76:3281
init @ vue.runtime.js?4b76:3112
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
(anonymous) @ app.js?6d40:19
./resources/js/app.js @ app.js?id=5d43c79e331d5c766823:680
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
0 @ app.js?id=5d43c79e331d5c766823:702
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
(anonymous) @ app.js?id=5d43c79e331d5c766823:196
(anonymous) @ app.js?id=5d43c79e331d5c766823:199
vue.runtime.js?4b76:1888 TypeError: Cannot read property 'app' of undefined
    at VueComponent.updatePageTitle (Layout.vue?a64b:45)
    at VueComponent.mounted (Layout.vue?a64b:41)
    at invokeWithErrorHandling (vue.runtime.js?4b76:1854)
    at callHook (vue.runtime.js?4b76:4205)
    at Object.insert (vue.runtime.js?4b76:3137)
    at invokeInsertHook (vue.runtime.js?4b76:6324)
    at VueComponent.patch [as __patch__] (vue.runtime.js?4b76:6541)
    at VueComponent.Vue._update (vue.runtime.js?4b76:3934)
    at VueComponent.updateComponent (vue.runtime.js?4b76:4052)
    at Watcher.get (vue.runtime.js?4b76:4463)
logError @ vue.runtime.js?4b76:1888
globalHandleError @ vue.runtime.js?4b76:1879
handleError @ vue.runtime.js?4b76:1839
invokeWithErrorHandling @ vue.runtime.js?4b76:1862
callHook @ vue.runtime.js?4b76:4205
insert @ vue.runtime.js?4b76:3137
invokeInsertHook @ vue.runtime.js?4b76:6324
patch @ vue.runtime.js?4b76:6541
Vue._update @ vue.runtime.js?4b76:3934
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
run @ vue.runtime.js?4b76:4538
flushSchedulerQueue @ vue.runtime.js?4b76:4296
(anonymous) @ vue.runtime.js?4b76:1980
flushCallbacks @ vue.runtime.js?4b76:1906
Promise.then (async)
timerFunc @ vue.runtime.js?4b76:1933
nextTick @ vue.runtime.js?4b76:1990
queueWatcher @ vue.runtime.js?4b76:4388
update @ vue.runtime.js?4b76:4528
notify @ vue.runtime.js?4b76:736
reactiveSetter @ vue.runtime.js?4b76:1061
(anonymous) @ app.js?439b:33
Promise.then (async)
(anonymous) @ app.js?439b:32
init @ inertia.js?0375:18
created @ app.js?439b:31
invokeWithErrorHandling @ vue.runtime.js?4b76:1854
callHook @ vue.runtime.js?4b76:4205
Vue._init @ vue.runtime.js?4b76:4987
VueComponent @ vue.runtime.js?4b76:5132
createComponentInstanceForVnode @ vue.runtime.js?4b76:3281
init @ vue.runtime.js?4b76:3112
createComponent @ vue.runtime.js?4b76:5956
createElm @ vue.runtime.js?4b76:5903
patch @ vue.runtime.js?4b76:6492
Vue._update @ vue.runtime.js?4b76:3931
updateComponent @ vue.runtime.js?4b76:4052
get @ vue.runtime.js?4b76:4463
Watcher @ vue.runtime.js?4b76:4452
mountComponent @ vue.runtime.js?4b76:4059
Vue.$mount @ vue.runtime.js?4b76:8390
(anonymous) @ app.js?6d40:19
./resources/js/app.js @ app.js?id=5d43c79e331d5c766823:680
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
0 @ app.js?id=5d43c79e331d5c766823:702
__webpack_require__ @ app.js?id=5d43c79e331d5c766823:64
(anonymous) @ app.js?id=5d43c79e331d5c766823:196
(anonymous) @ app.js?id=5d43c79e331d5c766823:199
vue.runtime.js?4b76:8410 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html`

**Comment by xoxoj** [comment] 2019-05-16 05:08
`TypeError: Cannot read property 'apply' of undefined`

**Comment by xoxoj** [comment] 2019-05-16 05:08
in app.js

`Vue.mixin({ methods: { route: (...args) => window.route(...args).url() } })`

**Comment by MichaelDeBoey** [comment] 2019-05-16 06:23
@xoxoj Thanks for taking your time to report a possible bug.

Can you please provide us with a reproduction repo so we have a little more context?

**Comment by reinink** [comment] 2019-05-16 12:20
Yep, we _need_ a repo that reproduces this.

**Comment by MichaelDeBoey** [comment] 2019-05-17 15:18
Hi @xoxoj!

Since we changed a lot of the code (both in the core & in the adapters) and so did our public API a bit, can you try again setting up a project following our README please?

If you still encounter problems be my guest to come back to me, but right now it's very hard for me to see what was possibly wrong, since we're working with Github dependencies instead of real semver ones.

`0.x` releases are [on their way](https://twitter.com/reinink/status/1129396432644059139), but have to struggle a bit with finding out bugs until then 😉

**Comment by reinink** [comment] 2019-05-18 11:34
Closing this for now to keep things tidy. If you share a working example of this issue, we'll be sure to have a look at it!

**Closed by reinink** 2019-05-18 11:34 UTC
